### ISSUE TITLE
feat: History, Prompt API (History 등록, 삭제, Prompt 등록, 리스트 기능 추가)

### ISSUE THREAD

**Issue by kimsungmo0108** [Team-S5T1/weasel-backend#23]
## 기능 요청

- History 등록, 삭제
- Prompt 등록, 리스트

## 예상 결과

- HTTP 요청으로 데이터 CRUD

## 추가 정보

- History, Prompt 컨트롤러 추가

**Comment by KKamJi98** [comment]
good luck
