### ISSUE TITLE
feat: Member Add

### ISSUE THREAD

**Issue by kimsungmo0108** [Team-S5T1/weasel-backend#3]
## 기능 요청

- 회원 등록 기능

## 예상 결과

- 사용자가 회원 등록 페이지를 통해 새로운 계정을 생성할 수 있다.
- 필수 입력 항목: 이메일, 비밀번호, 비밀번호 확인
- 선택 입력 항목: 사진 등록

## 추가 정보

- 이메일 주소는 고유해야 하며, DB에서 유니크 제약 조건 생성

**Comment by KKamJi98** [comment]
확인
